### ISSUE TITLE
Dockerise OSMOX

### ISSUE THREAD

**Issue by mfitz** [arup-group/osmox#20]
OSMOX depends on a number of native libraries such as [PROJ](https://proj.org/). These dependencies are platform-specific and can be tricky to install. For this reason, providing a Docker image of OSMOX would be helpful, since we can give the user a ready-made environment that already includes all the python dependencies as well as all of the underlying native dependencies, thus removing the pain of different means of installing the app on different platforms.

**Comment by DipayanP007** [comment]
Hey @mfitz I can work on this if you can give me commands needed to run the project

**Comment by ana-kop** [comment]
This was completed in this PR: https://github.com/arup-group/osmox/issues/20
