### ISSUE TITLE
Infill in landuse areas that have existing facilities

### ISSUE THREAD

**Issue by brynpickering** [arup-group/osmox#47]
### What can be improved?

When activity infilling, OSMOX currently ignores any landuse areas that contain facilities that have matching activities. There are cases when we want to infill because only a tiny proportion of a target area has facilities in it. Some ideas on how to do it:

1. Infill target areas that are already covered by < X% of a given activity type. E.g., if only 5% of the target area is already covered, then consider that area as requiring infilling.
2. Cut out the area taken up by existing facilities from a target area and infill only the new, smaller area. 

### Version

v0.2.0

**Comment by val-ismaili** [comment]
Yeah so I think on point 1, we want to be able to let the user input a reference dataset i.e. count of households in msoa. Ideally you have more detailed data but i think thats a good base point that should be common across most places. Presuming we input no additional landuse and just use OSM land-use, we can get OSMOX to check an intersection between the reference dataset and landuse. The area of residential landuse that is within an msoa polygon should have X houses, but osmox only finds <X, so we infill the difference in count within that portion of landuse within the msoa. There may be more than one resi landuse polygon in the msoa so we should look at totals.

**Comment by val-ismaili** [comment]
Point 2 - a generic dummy approach of randomly adding these houses within the defined area could be the default quick approach. As an alternative optional approach we can allow the user to input an additional reference dataset (such as the address points) where we can request OSMOX to sample address points that are within that same boundary intersection

**Comment by brynpickering** [comment]
> There may be more than one resi landuse polygon in the msoa so we should look at totals.

How would you imagine distributing across multiple landuse areas? proportion based on area?

**Comment by val-ismaili** [comment]
> Point 2 - a generic dummy approach of randomly adding these houses within the defined area could be the default quick approach. As an alternative optional approach we can allow the user to input an additional reference dataset (such as the address points) where we can request OSMOX to sample address points that are within that same boundary intersection

We can add an additional approach at this point 2 which if the user doesn't have a reference dataset to sample from AND isn't happy with houses not snapped to the road, they can turn on snapping to the road. i dont think this is feasible to be the default because of the scale but would be nice to enable as an option if focus area is small

**Comment by val-ismaili** [comment]
> > There may be more than one resi landuse polygon in the msoa so we should look at totals.
> 
> How would you imagine distributing across multiple landuse areas? proportion based on area?

yeah area seems reasonable
